coders: Move redefinition of RBG to hidden code block in djvu
This fixes the following redefinition warning with mingw toolchain
because RGB is a macro and defined in windgi.h file.

../coders/djvu.c:318: warning: "RGB" redefined
  318 | #define RGB 1
      |
wingdi.h:1397: note: this is the location of the previous definition
 1397 | #define RGB(r,g,b) ((COLORREF)(((BYTE)(r)|((WORD)((BYTE)(g))<<8))|(((DWORD)(BYTE)(b))<<16)))
      |